#!/usr/bin/env sh
# Windows setup, no WSL and no admin rights.
#
# Run it from Git Bash (or from an MSYS2 shell). It is idempotent: anything
# already present is reported and skipped.
#
#   ./setup.sh                 install everything
#   ./setup.sh --minimal       skip beads and goose (fleet mechanics only)
#
# What it does, and why each step exists, is in the README's Windows section.

set -e

DIR="$(cd "$(dirname "$0")/.." && pwd)"
. "$DIR/setup/common.sh"

MINIMAL=""
[ "$1" = "--minimal" ] && MINIMAL=1

MSYS2_URL="https://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz"
GOOSE_URL="https://github.com/block/goose/releases/latest/download/goose-x86_64-pc-windows-msvc.zip"
BIN="$HOME/.local/bin"

# MSYS2's own bash cannot be started from inside Git Bash: both carry a
# msys-2.0.dll and the two collide, which presents as a hang with no output and
# no error. powershell.exe is a native process, so it is a clean parent. This is
# the only reliable way to drive MSYS2 synchronously from here.
msys2_run() {
  powershell.exe -NoProfile -Command "& '$(cygpath -w "$MSYS2_ROOT/usr/bin/bash.exe")' -lc '$1'"
}

step "Where MSYS2 lives"
for candidate in "${MSYS2_ROOT:-}" "$HOME/msys64" "/c/msys64" "/c/tools/msys64"; do
  [ -n "$candidate" ] && [ -x "$candidate/usr/bin/bash.exe" ] && { MSYS2_ROOT="$candidate"; break; }
done

if [ -n "${MSYS2_ROOT:-}" ]; then
  say "found: $MSYS2_ROOT"
else
  MSYS2_ROOT="$HOME/msys64"
  say "not found — installing to $MSYS2_ROOT"
  say "the base archive is ~53 MB; the .exe installer is not used because it wants admin"
  command -v curl >/dev/null 2>&1 || { warn "curl is required"; exit 1; }
  command -v tar  >/dev/null 2>&1 || { warn "tar is required"; exit 1; }
  tmp="${TMPDIR:-/tmp}/msys2-base.tar.xz"
  curl -fsSL -o "$tmp" "$MSYS2_URL"
  tar -xJf "$tmp" -C "$HOME"
  rm -f "$tmp"
  [ -x "$MSYS2_ROOT/usr/bin/bash.exe" ] || { warn "extract did not produce $MSYS2_ROOT"; exit 1; }
  say "installed"
fi

step "Bootstrapping MSYS2"
# First run generates the pacman keyring. It is slow and it only happens once.
msys2_run 'true' >/dev/null 2>&1 || true
say "ready"

step "tmux and zsh"
if msys2_run 'command -v tmux >/dev/null && command -v zsh >/dev/null' >/dev/null 2>&1; then
  say "already installed: $(msys2_run 'tmux -V' 2>/dev/null | tr -d '\r')"
else
  say "installing via pacman"
  msys2_run 'pacman -Sy --noconfirm --needed tmux zsh' >/dev/null
  say "installed: $(msys2_run 'tmux -V' 2>/dev/null | tr -d '\r')"
fi

step "node"
if command -v node >/dev/null 2>&1; then
  say "found: $(node --version)"
else
  warn "node is not on PATH. fleet.sh needs it to read roles.yml."
  warn "install it from nodejs.org, then re-run this script."
  exit 1
fi

if [ -z "$MINIMAL" ]; then
  step "beads (issue tracking)"
  if command -v bd >/dev/null 2>&1; then
    say "found: $(bd --version 2>/dev/null | head -1)"
  else
    say "installing @beads/bd from npm"
    npm install -g @beads/bd >/dev/null 2>&1 && say "installed" || warn "npm install failed — board.mjs will not work until bd is present"
  fi

  step "goose (needed by the local, zero-spend profile)"
  if command -v goose >/dev/null 2>&1; then
    say "found: $(goose --version 2>/dev/null | tr -d ' \r')"
  else
    say "downloading the native Windows build (~80 MB)"
    mkdir -p "$BIN"
    tmp="${TMPDIR:-/tmp}/goose.zip"
    if curl -fsSL -o "$tmp" "$GOOSE_URL" && command -v unzip >/dev/null 2>&1; then
      unzip -o -q "$tmp" -d "$BIN"
      # The archive nests the binary one level down.
      [ -f "$BIN/goose-package/goose.exe" ] && mv "$BIN/goose-package/goose.exe" "$BIN/goose.exe" && rmdir "$BIN/goose-package" 2>/dev/null
      rm -f "$tmp"
      say "installed to $BIN"
    else
      warn "download or unzip failed — the local profile needs goose; install it by hand"
    fi
  fi
fi

step "The fleet command"
mkdir -p "$BIN"
MSYS2_WIN="$(cygpath -w "$MSYS2_ROOT")"
AFOX_POSIX="$(cygpath -u "$DIR" 2>/dev/null || printf '%s' "$DIR")"

# Three files, because the three shells resolve commands differently: cmd and
# PowerShell find fleet.cmd through PATHEXT, and Git Bash only finds an
# extensionless file. Both hand off to the same launcher.
cat > "$BIN/fleet-launch.sh" <<EOF
#!/usr/bin/env bash
# Generated by setup/windows.sh. Regenerate by re-running it.
#   \$1  directory the fleet should work on, Windows or POSIX form
#   \$2  roles profile; empty means whatever .env says
AFOX="$AFOX_POSIX"
SESSION=afox

DIR="\${1:-\$PWD}"
# A Windows-form path is something tmux cannot chdir to: it falls back to \$HOME
# with no error and every pane opens in the wrong tree.
case "\$DIR" in [A-Za-z]:*) DIR="\$(cygpath -u "\$DIR")" ;; esac
[ -d "\$DIR" ] || DIR="\$HOME"

if [ -n "\${2:-}" ]; then RUN="cd '\$DIR' && FLEET_ROLES='\$2' '\$AFOX/fleet.sh'"
else                      RUN="cd '\$DIR' && '\$AFOX/fleet.sh'"; fi

if tmux has-session -t "\$SESSION" 2>/dev/null; then
  # Re-spawn inside the session that exists rather than stacking up a new one;
  # fleet.sh kills its own window first, so this stays idempotent.
  tmux send-keys -t "\$SESSION:0" "\$RUN" Enter
  exec tmux attach -t "\$SESSION"
fi
exec tmux new-session -s "\$SESSION" -c "\$DIR" "\$RUN; exec bash -l"
EOF

cat > "$BIN/fleet.cmd" <<EOF
@echo off
rem Generated by setup/windows.sh. Start an afox fleet from cmd or PowerShell.
rem   fleet              the profile .env selects
rem   fleet roles.yml    a specific profile
setlocal
set "MSYS2_PATH_TYPE=inherit"
set "MSYSTEM=MSYS"
start "afox" "$MSYS2_WIN\\usr\\bin\\mintty.exe" -t "afox fleet" -s 200,50 /usr/bin/bash -l "$(cygpath -u "$BIN")/fleet-launch.sh" "%CD%" "%~1"
EOF

cat > "$BIN/fleet" <<'EOF'
#!/bin/sh
# Generated by setup/windows.sh. Git Bash shim.
# Goes through cmd.exe so MSYS2's bash never starts inside Git Bash's own
# process tree. /c not //c: the // form is for when path conversion is on.
MSYS_NO_PATHCONV=1 exec cmd.exe /c fleet.cmd "$@"
EOF

chmod +x "$BIN/fleet" "$BIN/fleet-launch.sh"
say "fleet, fleet.cmd, fleet-launch.sh -> $BIN"

case ":$PATH:" in
  *":$BIN:"*) : ;;
  *) warn "$BIN is not on PATH — add it, or the fleet command will not resolve" ;;
esac

step "Shell function inside MSYS2"
install_fleet_function "$DIR/fleet.sh" "$MSYS2_ROOT/home/$(msys2_run 'printf %s "$USER"' 2>/dev/null | tr -d '\r')/.bashrc"

step "Default profile"
if [ -f "$DIR/.env" ] && grep -q '^FLEET_ROLES=' "$DIR/.env"; then
  say "already set: $(grep '^FLEET_ROLES=' "$DIR/.env")"
else
  set_env_key "$DIR/.env" FLEET_ROLES roles.local.yml
  say "the local profile costs nothing; \`fleet roles.yml\` runs the hosted one"
fi

step "Two things this script cannot do for you"
say "Developer Mode (Settings > System > For developers) plus MSYS=winsymlinks:nativestrict"
say "  — without both, ln -s silently makes a COPY and ~/.tmux.conf stops tracking the repo"
say "ollama must be running with a model pulled:  ollama pull qwen3:8b"

printf '\nDone. From any shell, in the repo you want the fleet to work on:\n\n  fleet\n\n'
